changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: New Features ğŸ‰
      labels:
        - feature
    - title: Enhancements ğŸ‰
      labels:
        - enhancement
    - title: Fixes ğŸ‰
      labels:
        - bugfix
    - title: Dependencies ğŸ‰
      labels:
        - dependencies
    - title: Breaking Changes ğŸ‰
      labels:
        - breaking
    - title: Other Changes
      labels:
        - "*"
